import type { Character } from '@/lib/types'

export const CHARS: Character[] = [
  {
    id: 'aldric', nm: 'Aldric Forgebraise',
    sub: 'Guerrier · Humain · Niv.1',
    background: 'Soldat',
    bgDesc: 'Ancien garde de caravane. Maitrise militaire de vos armes.',
    bdg: 'bG', bt: 'GUERRIER',
    stats: { FOR: 17, DEX: 13, CON: 16, INT: 10, SAG: 13, CHA: 10 },
    hp: 13, hpMax: 13, ca: 18, init: '+1',
    saves: [{ n: 'FOR', v: '+5', p: 1 }, { n: 'DEX', v: '+1' }, { n: 'CON', v: '+5', p: 1 }, { n: 'INT', v: '+0' }, { n: 'SAG', v: '+1' }, { n: 'CHA', v: '+0' }],
    skills: [
      { n: 'Athletisme(FOR)', v: '+5' },
      { n: 'Intimidation(CHA)', v: '+2' },
      { n: 'Perception(SAG)', v: '+3' },
      { n: 'Survie(SAG)', v: '+3' },
    ],
    bgFeat: 'Costaud : +5 capacite transport, avantage jets FOR vs objets',
    weaponMastery: [
      { n: 'Épée longue', mastery: 'Sap', desc: 'Sap: cible a désavantage sur sa prochaine attaque jusqu\'à la fin de votre prochain tour' },
      { n: 'Arbalète légère', mastery: 'Slow', desc: 'Slow: vitesse de la cible -3m jusqu\'au début de votre prochain tour' },
    ],
    eq: [
      'Épée longue +1d8+5 tranchant (Versatile d10, Maîtrise Sap)',
      'Cotte de mailles CA 16',
      'Bouclier (+2 CA)',
      'Arbalète légère (1d8+1 perf., 24/96m, Maîtrise Slow)',
      '20 carreaux d\'arbalète',
      'Hachette (1d6+3 tranch., lancer 6/18m, Légère)',
      'Paquet d\'explorateur (sac, corde 15m, rations 10j, gourde, torches x10, briquet, pioche)',
      'Insigne militaire',
      'Dés à jouer en os',
      'Dagues de voyage x2',
      '10 po',
    ],
    atk: [
      { n: 'Épée longue (1 main)', b: '+5', d: '1d8+5 tranch.', note: '+Sap: désavantage prochaine attaque cible' },
      { n: 'Épée longue (2 mains)', b: '+5', d: '1d10+5 tranch.', note: 'Versatile, sans bouclier' },
      { n: 'Arbalète légère', b: '+3', d: '1d8+1 perf.', note: '24/96m, +Slow: -3m vitesse cible' },
      { n: 'Hachette', b: '+5', d: '1d6+3 tranch.', note: 'Lancer 6/18m, Légère' },
    ],
    feats: [
      '⚔ Style de combat : DUEL — +2 dégâts avec arme à 1 main si pas d\'autre arme (bouclier OK)',
      '💪 Second Souffle (1×/repos court) : ACTION BONUS → récupère 1d10+1 PV',
      '🗡 MAÎTRISE D\'ARMES 2024 : 2 armes avec propriétés de maîtrise (Épée longue=Sap, Arbalète légère=Slow)',
      '🛡 Maîtrises : toutes armures, boucliers, armes simples et de guerre',
      '🎯 Sauvegardes : FOR & CON maîtrisées (+BM)',
      '👤 Humain 2024 : Résolu (relance 1 échec par repos long), 1 compétence bonus, 1 don d\'origine',
      '📜 Background Soldat : compétences Athlétisme+Intimidation, outils jeux d\'échecs, don Costaud',
    ],
    sp: null,
    ks: [{ l: 'PV', v: '13' }, { l: 'CA', v: '18' }, { l: 'ATT', v: '+5' }],
    desc: 'Ancien garde de caravane. Maîtrise militaire, cœur loyal.',
  },
  {
    id: 'mira', nm: 'Sœur Mira',
    sub: 'Clerc · Halfeline · Niv.1',
    background: 'Acolyte',
    bgDesc: 'Élevée au temple. Savoir religieux et sens de la médecine.',
    bdg: 'bC', bt: 'CLERC',
    stats: { FOR: 10, DEX: 15, CON: 13, INT: 10, SAG: 17, CHA: 14 },
    hp: 9, hpMax: 9, ca: 16, init: '+2',
    saves: [{ n: 'FOR', v: '+0' }, { n: 'DEX', v: '+2' }, { n: 'CON', v: '+1' }, { n: 'INT', v: '+0' }, { n: 'SAG', v: '+5', p: 1 }, { n: 'CHA', v: '+4', p: 1 }],
    skills: [
      { n: 'Perspicacité(SAG)', v: '+5' },
      { n: 'Médecine(SAG)', v: '+5' },
      { n: 'Religion(INT)', v: '+2' },
    ],
    bgFeat: 'Éveil magique : apprend un sort mineur de votre classe',
    weaponMastery: [
      { n: 'Masse', mastery: 'Sap', desc: 'Sap: cible a désavantage sur sa prochaine attaque' },
    ],
    eq: [
      'Masse (1d6 contondant, Maîtrise Sap)',
      'Armure d\'écailles CA 14+DEX(max+2)=16',
      'Bouclier (+2 CA — Non cumulable avec écailles = CA 16)',
      'Symbole sacré (emblème de l\'Unité)',
      'Paquet de prêtre (sac, couverture, bougies x10, boîte à aumône, encens, huile, tome de prières)',
      'Livre de prières',
      'Bandelettes cérémonielles',
      'Rations 5j, gourde',
      '10 po',
    ],
    atk: [
      { n: 'Masse', b: '+2', d: '1d6 cont.', note: '+Sap: désavantage prochaine attaque cible' },
      { n: 'Flamme sacrée (sort mineur)', b: 'save DEX DD13', d: '1d8 radiant', note: 'Portée 18m, ignore couverture' },
      { n: 'Guide (sort mineur)', b: 'contact', d: '+1d4 prochain jet d\'Attr.', note: 'Conc. 1min, allié' },
    ],
    feats: [
      '📿 Incantation divine (SAG) : DD sorts 13, bonus attaque sorts +5',
      '🔹 Emplacements : 2 × niveau 1 · 3 sorts mineurs · 4 sorts préparés',
      '📖 Sorts 2024 — préparation flexible : au repos long, choisir 4 sorts parmi la liste de Clerc pour les préparer',
      '✨ Sous-classe (Domaine divin) : CHOIX AU NIVEAU 3 (non disponible au niveau 1)',
      '🛡 Maîtrises 2024 : armures légères/intermédiaires, boucliers, armes simples',
      '🍀 Halfeline 2024 : CHANCEUX (relance 1 naturel), BRAVE (avantage saves vs Terrifié), AGILITÉ (traverse case plus grand)',
      '🗡 MAÎTRISE D\'ARMES 2024 : Masse (Sap)',
      '📜 Background Acolyte : Perspicacité+Religion, maîtrise outils calligraphe, don Éveil magique',
    ],
    sp: {
      ab: 'SAG', dc: 13, att: '+5',
      sl: { 1: 2 }, us: { 1: 0 },
      cants: [
        'Flamme sacrée (1d8 rad, save DEX DD13, portée 18m, ignore couverture)',
        'Lumière (objet brille 6m rayon, 1h, sans conc.)',
        'Guide (+1d4 au prochain jet de caract., conc. 1min)',
        'Stabilisation (contact, stabilise inconscient à 1PV minimum effectif)',
      ],
      prep: [
        'Bénédiction (conc. 1min, 3 cibles, +1d4 jets attaque & saves, 1 empl.)',
        'Soins (contact, 1d8+3 PV, 1 empl.)',
        'Commandement (SAG DD13, 1 mot: Fuis/Tombe/Approche/Lâche/Stoppe, portée 18m, 1 empl.)',
        'Mot de guérison (ACTION BONUS, portée 18m, 1d4+3 PV, 1 empl.)',
      ],
    },
    ks: [{ l: 'PV', v: '9' }, { l: 'CA', v: '16' }, { l: 'SOIN', v: '1d8+3' }],
    desc: 'Acolyte dévouée. Volonté de fer sous un sourire paisible.',
  },
  {
    id: 'corvin', nm: 'Corvin l\'Ombre',
    sub: 'Roublard · Demi-Elfe · Niv.1',
    background: 'Criminel',
    bgDesc: 'Informateur et cambrioleur reconverti. Connait la pègre.',
    bdg: 'bR', bt: 'ROUBLARD',
    stats: { FOR: 9, DEX: 17, CON: 14, INT: 13, SAG: 11, CHA: 16 },
    hp: 10, hpMax: 10, ca: 15, init: '+3',
    saves: [{ n: 'FOR', v: '-1' }, { n: 'DEX', v: '+5', p: 1 }, { n: 'CON', v: '+2' }, { n: 'INT', v: '+3', p: 1 }, { n: 'SAG', v: '+0' }, { n: 'CHA', v: '+3' }],
    skills: [
      { n: 'Discrétion(DEX) EXPERTISE', v: '+7' },
      { n: 'Tromperie(CHA) EXPERTISE', v: '+7' },
      { n: 'Perception(SAG)', v: '+2' },
      { n: 'Persuasion(CHA)', v: '+5' },
      { n: 'Investigation(INT)', v: '+3' },
      { n: 'Perspicacité(SAG)', v: '+2' },
    ],
    bgFeat: 'Furtif : compétences Discrétion et Tromperie, outils de voleur',
    weaponMastery: [
      { n: 'Rapière', mastery: 'Vex', desc: 'Vex: si vous touchez, avantage sur votre prochaine attaque contre la même cible' },
    ],
    eq: [
      'Rapière (1d8+3 perforant, Finesse, Maîtrise Vex)',
      'Arc court (1d6+3 perforant, 24/96m, Maîtrise Vex)',
      '20 flèches',
      'Armure de cuir CA 11+DEX=14+ou CA 15 avec cuir clouté — CA 15',
      'Dagues x2 (1d4+3 perf., Finesse, Légère, Lancer 6/18m)',
      'Outils de voleur (maîtrisés — crocheter, désamorcer)',
      'Paquet de cambrioleur (sac, bille, grelot, corde 15m, lanterne, pioche, burin, pieds-de-biche)',
      'Vêtement noir à capuche',
      'Pochette (15po)',
    ],
    atk: [
      { n: 'Rapière', b: '+5', d: '1d8+3 perf. (+1d6 sournoise*)', note: 'Finesse, +Vex: avantage prochaine attaque même cible' },
      { n: 'Arc court', b: '+5', d: '1d6+3 perf. (+1d6 sournoise*)', note: '24/96m, +Vex' },
      { n: 'Dague', b: '+5', d: '1d4+3 perf. (+1d6 sournoise*)', note: 'Finesse, Légère, Lancer 6/18m' },
    ],
    feats: [
      '🗡 ATTAQUE SOURNOISE 1d6 : 1×/tour, +1d6 dmg si avantage OU allié adjacent cible (sans désavantage sur attaque)',
      '🎭 EXPERTISE (niv.1) : Discrétion +7, Tromperie +7 (double maîtrise)',
      '🗝 Argot des voleurs : langage secret criminel',
      '🔓 Outils de voleur : maîtrisés (crocheter serrures, désamorcer pièges)',
      '🗡 MAÎTRISE D\'ARMES 2024 : Rapière & Arc court (Vex)',
      '🧝 Demi-Elfe 2024 : Vision dans le noir 18m, Ascendance féerique (avantage saves vs Charmé, immunité sommeil magique), +2 compétences',
      '📜 Background Criminel : Discrétion+Tromperie, outils de voleur+jeu de cartes, don Furtif',
    ],
    sp: null,
    ks: [{ l: 'PV', v: '10' }, { l: 'CA', v: '15' }, { l: 'FURT', v: '+7' }],
    desc: 'Informateur reconverti. Parle à tous, fait confiance à personne.',
  },
  {
    id: 'elysa', nm: 'Elysa Ventbris',
    sub: 'Magicienne · Elfe Haut-Elfe · Niv.1',
    background: 'Sage',
    bgDesc: 'Étudiante d\'une académie arcanique exilée. Érudite.',
    bdg: 'bM', bt: 'MAGE',
    stats: { FOR: 8, DEX: 16, CON: 13, INT: 17, SAG: 12, CHA: 10 },
    hp: 7, hpMax: 7, ca: 13, init: '+3',
    saves: [{ n: 'FOR', v: '-1' }, { n: 'DEX', v: '+3' }, { n: 'CON', v: '+1' }, { n: 'INT', v: '+5', p: 1 }, { n: 'SAG', v: '+3', p: 1 }, { n: 'CHA', v: '+0' }],
    skills: [
      { n: 'Arcanes(INT)', v: '+5' },
      { n: 'Histoire(INT)', v: '+5' },
      { n: 'Investigation(INT)', v: '+5' },
      { n: 'Perception racial(SAG)', v: '+3' },
    ],
    bgFeat: 'Initié à la magie (Magicien) : 2 sorts mineurs + 1 sort niv.1 supplémentaire',
    weaponMastery: [
      { n: 'Bâton', mastery: 'Topple', desc: 'Topple: save CON ou cible Renversée (Prone)' },
      { n: 'Dague', mastery: 'Nick', desc: 'Nick: peut attaquer avec une arme Légère sans action bonus' },
    ],
    eq: [
      'Bâton (1d6-1 contondant, Versatile 1d8, Maîtrise Topple)',
      'Dague (1d4-1 perf., Finesse, Légère, Lancer 6/18m, Maîtrise Nick)',
      'Grimoire (6 sorts niv.1 copiés)',
      'Focalisateur arcanique (cristal)',
      'Composantes matérielles (sachet)',
      'Paquet de savant (sac, livre de savoir, encre x2, plume, parchemins x10, sablier, petit couteau)',
      'Livre de souvenirs (background Sage)',
      'Pochette 10po',
    ],
    atk: [
      { n: 'Projectile magique', b: 'AUTO', d: '3 × (1d4+1) force', note: '3 fléchettes auto, portée 36m, 1 empl. niv.1' },
      { n: 'Rayon de givre (mineur)', b: '+5', d: '1d8 froid', note: 'Portée 18m, vitesse cible -3m si touché' },
      { n: 'Trait de feu (mineur)', b: '+5', d: '1d10 feu', note: 'Portée 36m' },
      { n: 'Bâton', b: '+1', d: '1d6-1 cont.', note: 'Versatile 1d8-1, +Topple save CON DD 9' },
      { n: 'Dague', b: '+3', d: '1d4-1 perf.', note: 'Finesse, Légère, +Nick' },
    ],
    feats: [
      '📚 GRIMOIRE : Armure du mage, Bouclier, Projectile magique, Charme-personne, Identification★, Sommeil',
      '✨ Sorts préparés (INT+niv = 5) : choisit 5 parmi grimoire chaque matin',
      '🔮 Incantation arcanique (INT) : DD sorts 13, bonus attaque sorts +5, 2 empl. niv.1',
      '🔁 Récupération arcanique (1×/repos court) : récupère emplacements totalisant ≤ 1 (donc 1 empl. niv.1)',
      '🗡 MAÎTRISE D\'ARMES 2024 : Bâton (Topple), Dague (Nick)',
      '🧝 Elfe Haut-Elfe 2024 : Vision dans le noir 18m, Perception maîtrisée, Ascendance féerique, Transe(4h=repos 8h), CANTRIP BONUS (un sort mineur de Magicien inclus)',
      '✦ Sort mineur racial (Haut-Elfe) : Prestidigitation (petits effets cosmétiques)',
      '📜 Background Sage : Arcanes+Histoire, outils calligraphe, don Initié à la magie',
      '★ Identification = rituel (10min, sans emplacement)',
    ],
    sp: {
      ab: 'INT', dc: 13, att: '+5',
      sl: { 1: 2 }, us: { 1: 0 },
      cants: [
        'Trait de feu (1d10 feu, portée 36m)',
        'Rayon de givre (1d8 froid + vitesse cible -3m, portée 18m)',
        'Illusion mineure (son ou image statique, 1min, portée 9m)',
        'Prestidigitation (effets mineurs, racial Haut-Elfe)',
      ],
      prep: [
        'Armure du mage (action, CA 13+DEX=16 pendant 8h, non-conc., 1 empl. niv.1)',
        'Bouclier (RÉACTION, +5 CA jusqu\'au prochain tour OU annule Projectile magique, 1 empl. niv.1)',
        'Projectile magique (3 fléchettes × 1d4+1 force auto, portée 36m, 1 empl. niv.1)',
        'Charme-personne (save SAG DD13, Charmé 1h, portée 9m, 1 empl. niv.1)',
        'Sommeil 2024 (save SAG DD13, sphère 1,5m portée 27m, créatures touchées subissent Incapacité jusqu\'à fin de votre prochain tour, tombent Prone, 1 empl. niv.1)',
      ],
    },
    ks: [{ l: 'PV', v: '7' }, { l: 'CA', v: '13/16*' }, { l: 'DD', v: '13' }],
    desc: 'Érudite exilée. Fragile mais redoutable à distance.',
  },
]
