import type { SpeciesData, ClassData, BackgroundData, SpeciesId, ClassId, BackgroundId } from './srd-types'

export const ALL_SKILLS = [
  'Acrobatics', 'Animal Handling', 'Arcana', 'Athletics', 'Deception', 'History',
  'Insight', 'Intimidation', 'Investigation', 'Medicine', 'Nature', 'Perception',
  'Performance', 'Persuasion', 'Religion', 'Sleight of Hand', 'Stealth', 'Survival',
]

export const SPECIES: Record<SpeciesId, SpeciesData> = {
  human: {
    name: 'Human',
    description: 'Adaptable and ambitious. Gain an extra skill proficiency, Heroic Inspiration after each long rest, and an Origin feat.',
    speed: 30,
    size: 'Medium',
    traits: [
      { name: 'Heroic Inspiration', description: 'Gain Heroic Inspiration after finishing a Long Rest.' },
      { name: 'Skillful', description: 'Gain proficiency in one skill of your choice.' },
      { name: 'Versatile', description: 'Gain the Skilled or Alert origin feat.' },
    ],
    subraces: null,
  },
  elf: {
    name: 'Elf',
    description: 'Graceful and long-lived, with keen senses and fey heritage.',
    speed: 30,
    size: 'Medium',
    traits: [
      { name: 'Darkvision', description: '60 ft.' },
      { name: 'Fey Ancestry', description: 'Advantage on saves vs. Charmed. Immune to magical sleep.' },
      { name: 'Keen Senses', description: 'Proficiency in Perception.' },
      { name: 'Trance', description: '4 hours of meditation replaces 8 hours of sleep.' },
    ],
    subraces: {
      high_elf: { name: 'High Elf', extra: 'Know one Wizard cantrip (INT). Proficiency in longsword, shortsword, shortbow, longbow.' },
      wood_elf: { name: 'Wood Elf', extra: 'Speed 35 ft. Mask of the Wild: hide when lightly obscured by nature. Proficiency in longsword, shortsword, shortbow, longbow.' },
      drow: { name: 'Drow', extra: 'Darkvision 120 ft. Sunlight Sensitivity. Know Dancing Lights cantrip. Proficiency in rapier, shortsword, hand crossbow.' },
    },
  },
  dwarf: {
    name: 'Dwarf',
    description: 'Hardy and resilient, with ancient ties to stone and craft.',
    speed: 30,
    size: 'Medium',
    traits: [
      { name: 'Darkvision', description: '120 ft.' },
      { name: 'Dwarven Resilience', description: 'Resistance to poison damage. Advantage on saves vs. poison.' },
      { name: 'Stonecunning', description: 'Tremorsense 60 ft for 10 minutes, usable PB times per long rest.' },
      { name: 'Dwarven Toughness', description: '+1 HP per level (Hill Dwarf only).' },
    ],
    subraces: {
      hill_dwarf: { name: 'Hill Dwarf', extra: 'Dwarven Toughness: +1 HP per level.' },
      mountain_dwarf: { name: 'Mountain Dwarf', extra: 'Proficiency in light and medium armor.' },
    },
  },
  halfling: {
    name: 'Halfling',
    description: 'Small but lucky and surprisingly fearless.',
    speed: 30,
    size: 'Small',
    traits: [
      { name: 'Lucky', description: 'When you roll a 1 on a d20 test, reroll and use the new result.' },
      { name: 'Brave', description: 'Advantage on saves vs. Frightened.' },
      { name: 'Halfling Nimbleness', description: 'Can move through the space of any creature larger than you.' },
    ],
    subraces: {
      lightfoot: { name: 'Lightfoot', extra: 'Naturally Stealthy: can hide behind creatures larger than you.' },
      stout: { name: 'Stout', extra: 'Stout Resilience: advantage on saves vs. poison, resistance to poison damage.' },
    },
  },
  gnome: {
    name: 'Gnome',
    description: 'Curious, inventive, and magically gifted.',
    speed: 30,
    size: 'Small',
    traits: [
      { name: 'Darkvision', description: '60 ft.' },
      { name: 'Gnomish Cunning', description: 'Advantage on INT, WIS, CHA saves vs. magic.' },
    ],
    subraces: {
      forest_gnome: { name: 'Forest Gnome', extra: 'Know Minor Illusion cantrip. Speak with Small Beasts.' },
      rock_gnome: { name: 'Rock Gnome', extra: 'Proficiency in History and Tinker\'s Tools. Can craft tiny clockwork devices.' },
    },
  },
  half_elf: {
    name: 'Half-Elf',
    description: 'Part human, part elf — belonging to both worlds and neither.',
    speed: 30,
    size: 'Medium',
    traits: [
      { name: 'Darkvision', description: '60 ft.' },
      { name: 'Fey Ancestry', description: 'Advantage on saves vs. Charmed. Immune to magical sleep.' },
      { name: 'Skill Versatility', description: 'Gain proficiency in two skills of your choice.' },
    ],
    subraces: null,
  },
  half_orc: {
    name: 'Half-Orc',
    description: 'Tough, powerful, and built to survive.',
    speed: 30,
    size: 'Medium',
    traits: [
      { name: 'Darkvision', description: '60 ft.' },
      { name: 'Relentless Endurance', description: 'When reduced to 0 HP, drop to 1 HP instead. 1/long rest.' },
      { name: 'Savage Attacks', description: 'On a critical hit with a melee weapon, roll one weapon damage die extra.' },
      { name: 'Adrenaline Rush', description: 'Dash as a bonus action, gain temp HP equal to PB. PB times per long rest.' },
    ],
    subraces: null,
  },
  tiefling: {
    name: 'Tiefling',
    description: 'Infernal heritage marks you — but your fate is your own.',
    speed: 30,
    size: 'Medium',
    traits: [
      { name: 'Darkvision', description: '60 ft.' },
      { name: 'Hellish Resistance', description: 'Resistance to fire damage.' },
      { name: 'Infernal Legacy', description: 'Know Thaumaturgy cantrip. At level 3: cast Hellish Rebuke 1/long rest. At level 5: cast Darkness 1/long rest.' },
    ],
    subraces: null,
  },
  dragonborn: {
    name: 'Dragonborn',
    description: 'Draconic power runs through your blood.',
    speed: 30,
    size: 'Medium',
    traits: [
      { name: 'Darkvision', description: '60 ft.' },
      { name: 'Breath Weapon', description: 'Exhale destructive energy (damage type based on ancestry). PB times per long rest. DC = 8 + CON mod + PB.' },
      { name: 'Draconic Ancestry', description: 'Choose a dragon type: determines breath weapon damage type and resistance.' },
      { name: 'Damage Resistance', description: 'Resistance to your ancestry\'s damage type.' },
    ],
    subraces: null,
  },
}

export const CLASSES: Record<ClassId, ClassData> = {
  barbarian: {
    name: 'Barbarian',
    description: 'A fierce warrior fueled by primal rage.',
    playstyle: 'Wade into melee, shrug off damage, hit harder the longer you fight.',
    hit_die: 12,
    hp_at_1: 12,
    armor_profs: ['Light armor', 'Medium armor', 'Shields'],
    weapon_profs: ['Simple weapons', 'Martial weapons'],
    saving_throws: ['str', 'con'],
    skill_choices: { count: 2, from: ['Animal Handling', 'Athletics', 'Intimidation', 'Nature', 'Perception', 'Survival'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Rage', description: 'Bonus action: enter a rage for 1 minute — advantage on STR checks/saves, bonus melee damage, resistance to bludgeoning/piercing/slashing. 2 uses, recharges on long rest.', recharge: 'long_rest', uses: 2 },
      { name: 'Unarmored Defense', description: 'While not wearing armor, AC = 10 + DEX mod + CON mod.' },
      { name: 'Weapon Mastery', description: 'Apply the mastery property of two weapon types you\'re proficient with.' },
    ],
    equipment_options: [
      ['Greataxe', '4 handaxes', 'Explorer\'s pack', '10 gp'],
      ['Any martial melee weapon', 'Shield', '4 javelins', 'Explorer\'s pack', '10 gp'],
    ],
    is_caster: false,
  },
  bard: {
    name: 'Bard',
    description: 'A performer whose art carries real magic.',
    playstyle: 'Flexible support and skill-monkey — buff allies, debuff enemies, cover any gap.',
    hit_die: 8,
    hp_at_1: 8,
    armor_profs: ['Light armor'],
    weapon_profs: ['Simple weapons', 'Hand crossbows', 'Longswords', 'Rapiers', 'Shortswords'],
    saving_throws: ['dex', 'cha'],
    skill_choices: { count: 3, from: ['Acrobatics', 'Animal Handling', 'Arcana', 'Athletics', 'Deception', 'History', 'Insight', 'Intimidation', 'Investigation', 'Medicine', 'Nature', 'Perception', 'Performance', 'Persuasion', 'Religion', 'Sleight of Hand', 'Stealth', 'Survival'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Bardic Inspiration', description: 'Bonus action: give an ally a d6 they can add to one ability check, attack roll, or save. Uses = CHA mod (min 1), recharges on long rest.', recharge: 'long_rest' },
      { name: 'Spellcasting', description: 'Cast Bard spells using CHA.' },
    ],
    equipment_options: [
      ['Leather armor', 'Rapier', 'Musical instrument', 'Entertainer\'s pack', '10 gp'],
      ['Leather armor', 'Simple weapon', 'Musical instrument', 'Diplomat\'s pack', '10 gp'],
    ],
    is_caster: true,
    spellcasting_ability: 'cha',
    cantrips_known: 2,
    spells_known_at_1: 4,
    spell_slots_at_1: { 1: 2 },
    spell_list_at_1: ['Charm Person', 'Comprehend Languages', 'Cure Wounds', 'Detect Magic', 'Disguise Self', 'Faerie Fire', 'Feather Fall', 'Healing Word', 'Heroism', 'Sleep', 'Tasha\'s Hideous Laughter', 'Thunderwave'],
    cantrip_list: ['Dancing Lights', 'Friends', 'Mage Hand', 'Mending', 'Message', 'Minor Illusion', 'Prestidigitation', 'True Strike', 'Vicious Mockery'],
  },
  cleric: {
    name: 'Cleric',
    description: 'A conduit of divine power, healer and warrior in one.',
    playstyle: 'Keep the party alive while holding your own in melee.',
    hit_die: 8,
    hp_at_1: 8,
    armor_profs: ['Light armor', 'Medium armor', 'Shields'],
    weapon_profs: ['Simple weapons'],
    saving_throws: ['wis', 'cha'],
    skill_choices: { count: 2, from: ['History', 'Insight', 'Medicine', 'Persuasion', 'Religion'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Spellcasting', description: 'Cast Cleric spells using WIS. Prepare spells each long rest (level + WIS mod).' },
      { name: 'Divine Order', description: 'Choose Protector (proficiency with martial weapons and heavy armor) or Thaumaturge (extra cantrip, boosted Religion checks).' },
    ],
    equipment_options: [
      ['Chain shirt', 'Shield', 'Mace', 'Holy symbol', 'Priest\'s pack', '10 gp'],
      ['Leather armor', 'Mace', 'Holy symbol', 'Priest\'s pack', '15 gp'],
    ],
    is_caster: true,
    spellcasting_ability: 'wis',
    cantrips_known: 3,
    spells_known_at_1: 4,
    spell_slots_at_1: { 1: 2 },
    spell_list_at_1: ['Bless', 'Cure Wounds', 'Command', 'Detect Evil and Good', 'Guiding Bolt', 'Healing Word', 'Inflict Wounds', 'Protection from Evil and Good', 'Sanctuary', 'Shield of Faith'],
    cantrip_list: ['Guidance', 'Light', 'Mending', 'Resistance', 'Sacred Flame', 'Spare the Dying', 'Thaumaturgy'],
  },
  druid: {
    name: 'Druid',
    description: 'A guardian of the natural world who can take animal shape.',
    playstyle: 'Adaptable spellcaster, strong outdoors, can wild shape into a beast in a pinch.',
    hit_die: 8,
    hp_at_1: 8,
    armor_profs: ['Light armor', 'Medium armor', 'Shields (non-metal)'],
    weapon_profs: ['Clubs', 'Daggers', 'Darts', 'Javelins', 'Maces', 'Quarterstaffs', 'Scimitars', 'Sickles', 'Slings', 'Spears'],
    saving_throws: ['int', 'wis'],
    skill_choices: { count: 2, from: ['Arcana', 'Animal Handling', 'Insight', 'Medicine', 'Nature', 'Perception', 'Religion', 'Survival'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Spellcasting', description: 'Cast Druid spells using WIS. Prepare spells each long rest (level + WIS mod).' },
      { name: 'Druidic', description: 'Know the secret language of druids.' },
      { name: 'Primal Order', description: 'Choose Magician (extra cantrip, boosted Nature/Religion checks) or Warden (martial weapon and medium armor proficiency).' },
    ],
    equipment_options: [
      ['Leather armor', 'Sickle', 'Druidic focus', 'Explorer\'s pack', '10 gp'],
      ['Hide armor', 'Quarterstaff', 'Druidic focus', 'Explorer\'s pack', '10 gp'],
    ],
    is_caster: true,
    spellcasting_ability: 'wis',
    cantrips_known: 2,
    spells_known_at_1: 4,
    spell_slots_at_1: { 1: 2 },
    spell_list_at_1: ['Animal Friendship', 'Charm Person', 'Cure Wounds', 'Entangle', 'Faerie Fire', 'Fog Cloud', 'Healing Word', 'Speak with Animals', 'Thunderwave'],
    cantrip_list: ['Druidcraft', 'Guidance', 'Mending', 'Poison Spray', 'Produce Flame', 'Resistance', 'Shillelagh'],
  },
  fighter: {
    name: 'Fighter',
    description: 'Master of weapons and armor. The most versatile martial class.',
    playstyle: 'Get in close, absorb punishment, deal it back.',
    hit_die: 10,
    hp_at_1: 10,
    armor_profs: ['Light armor', 'Medium armor', 'Heavy armor', 'Shields'],
    weapon_profs: ['Simple weapons', 'Martial weapons'],
    saving_throws: ['str', 'con'],
    skill_choices: { count: 2, from: ['Acrobatics', 'Animal Handling', 'Athletics', 'History', 'Insight', 'Intimidation', 'Perception', 'Survival'] },
    subclass_at_1: {
      label: 'Fighting Style',
      options: [
        { id: 'archery', name: 'Archery', description: '+2 bonus to attack rolls with ranged weapons.' },
        { id: 'defense', name: 'Defense', description: '+1 AC while wearing armor.' },
        { id: 'dueling', name: 'Dueling', description: '+2 damage when wielding a melee weapon in one hand and no other weapon.' },
        { id: 'great_weapon', name: 'Great Weapon Fighting', description: 'Reroll 1s and 2s on weapon damage dice when using a two-handed weapon.' },
        { id: 'protection', name: 'Protection', description: 'When a creature you can see attacks a target near you, impose disadvantage (uses reaction + shield).' },
        { id: 'two_weapon', name: 'Two-Weapon Fighting', description: 'Add ability modifier to off-hand attack damage.' },
      ],
    },
    features_at_1: [
      { name: 'Second Wind', description: 'Bonus action: regain 1d10 + Fighter level HP. Recharges on short rest.', recharge: 'short_rest', uses: 1 },
    ],
    equipment_options: [
      ['Chain mail', 'Longsword', 'Shield', '4 javelins', 'Explorer\'s pack', '10 gp'],
      ['Leather armor', 'Longbow', '20 arrows', '2 shortswords', 'Explorer\'s pack', '10 gp'],
    ],
    is_caster: false,
  },
  monk: {
    name: 'Monk',
    description: 'A martial artist who channels inner discipline into supernatural martial prowess.',
    playstyle: 'Fast, mobile striker — hit multiple times, dodge everything, no armor needed.',
    hit_die: 8,
    hp_at_1: 8,
    armor_profs: [],
    weapon_profs: ['Simple weapons', 'Shortswords'],
    saving_throws: ['str', 'dex'],
    skill_choices: { count: 2, from: ['Acrobatics', 'Athletics', 'History', 'Insight', 'Religion', 'Stealth'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Martial Arts', description: 'Unarmed strikes and monk weapons use DEX if higher, deal 1d6, and unarmed strikes can be a bonus action.' },
      { name: 'Unarmored Defense', description: 'While not wearing armor or a shield, AC = 10 + DEX mod + WIS mod.' },
    ],
    equipment_options: [
      ['Spear', '5 darts', 'Explorer\'s pack'],
      ['Any simple weapon', '5 darts', 'Explorer\'s pack'],
    ],
    is_caster: false,
  },
  paladin: {
    name: 'Paladin',
    description: 'A warrior bound by a sacred oath, backed by divine magic.',
    playstyle: 'Front-line tank with burst healing and smiting power.',
    hit_die: 10,
    hp_at_1: 10,
    armor_profs: ['Light armor', 'Medium armor', 'Heavy armor', 'Shields'],
    weapon_profs: ['Simple weapons', 'Martial weapons'],
    saving_throws: ['wis', 'cha'],
    skill_choices: { count: 2, from: ['Athletics', 'Insight', 'Intimidation', 'Medicine', 'Persuasion', 'Religion'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Lay on Hands', description: 'A pool of healing equal to 5 × level (5 at level 1), usable as an action to restore HP or cure a disease/poison. Recharges on long rest.', recharge: 'long_rest' },
      { name: 'Weapon Mastery', description: 'Apply the mastery property of two weapon types you\'re proficient with.' },
    ],
    equipment_options: [
      ['Chain mail', 'Longsword', 'Shield', '6 javelins', 'Holy symbol', '10 gp'],
      ['Leather armor', 'Simple weapon', 'Holy symbol', 'Priest\'s pack', '10 gp'],
    ],
    is_caster: false,
  },
  ranger: {
    name: 'Ranger',
    description: 'A hunter and wilderness scout, equally deadly at range or in the brush.',
    playstyle: 'Ranged skirmisher with strong tracking and survival skills.',
    hit_die: 10,
    hp_at_1: 10,
    armor_profs: ['Light armor', 'Medium armor', 'Shields'],
    weapon_profs: ['Simple weapons', 'Martial weapons'],
    saving_throws: ['str', 'dex'],
    skill_choices: { count: 3, from: ['Animal Handling', 'Athletics', 'Insight', 'Investigation', 'Nature', 'Perception', 'Stealth', 'Survival'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Favored Enemy', description: 'Know a spell from the Druid list (per Origin feat), and gain advantage on Survival checks to track your quarry.' },
      { name: 'Weapon Mastery', description: 'Apply the mastery property of two weapon types you\'re proficient with.' },
    ],
    equipment_options: [
      ['Leather armor', 'Longbow', '20 arrows', '2 shortswords', 'Explorer\'s pack', '10 gp'],
      ['Scale mail', 'Shortsword', 'Shortbow', '20 arrows', 'Explorer\'s pack', '10 gp'],
    ],
    is_caster: false,
  },
  rogue: {
    name: 'Rogue',
    description: 'A specialist in stealth, precision strikes, and getting away with it.',
    playstyle: 'Skill-focused striker — scout ahead, pick locks, and burst down one target at a time.',
    hit_die: 8,
    hp_at_1: 8,
    armor_profs: ['Light armor'],
    weapon_profs: ['Simple weapons', 'Hand crossbows', 'Longswords', 'Rapiers', 'Shortswords'],
    saving_throws: ['dex', 'int'],
    skill_choices: { count: 4, from: ['Acrobatics', 'Athletics', 'Deception', 'Insight', 'Intimidation', 'Investigation', 'Perception', 'Performance', 'Persuasion', 'Sleight of Hand', 'Stealth'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Expertise', description: 'Double proficiency bonus on two skill proficiencies (or one skill + thieves\' tools).' },
      { name: 'Sneak Attack', description: 'Once per turn, deal an extra 1d6 damage on an attack with advantage or with an ally adjacent to the target.' },
      { name: 'Thieves\' Cant', description: 'Know the secret rogue argot and its hidden signs.' },
      { name: 'Weapon Mastery', description: 'Apply the mastery property of two weapon types you\'re proficient with.' },
    ],
    equipment_options: [
      ['Leather armor', 'Rapier', 'Shortbow', '20 arrows', 'Burglar\'s pack', 'Thieves\' tools', '10 gp'],
      ['Leather armor', '2 daggers', 'Shortsword', 'Burglar\'s pack', 'Thieves\' tools', '10 gp'],
    ],
    is_caster: false,
  },
  sorcerer: {
    name: 'Sorcerer',
    description: 'A spellcaster whose magic is innate, born of blood or a strange event.',
    playstyle: 'Small but potent spell list, reshaped on the fly with Metamagic.',
    hit_die: 6,
    hp_at_1: 6,
    armor_profs: [],
    weapon_profs: ['Daggers', 'Darts', 'Slings', 'Quarterstaffs', 'Light crossbows'],
    saving_throws: ['con', 'cha'],
    skill_choices: { count: 2, from: ['Arcana', 'Deception', 'Insight', 'Intimidation', 'Persuasion', 'Religion'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Spellcasting', description: 'Cast Sorcerer spells using CHA.' },
      { name: 'Innate Sorcery', description: 'Bonus action: for 1 minute, your spell save DC and spell attack bonus each gain +1, and any spell you cast with a 1st-level slot uses no slot the first time each turn. 2 uses, recharges on long rest.', recharge: 'long_rest', uses: 2 },
    ],
    equipment_options: [
      ['Light crossbow', '20 bolts', 'Arcane focus', 'Dungeoneer\'s pack', '10 gp'],
      ['Simple weapon', 'Arcane focus', 'Dungeoneer\'s pack', '10 gp'],
    ],
    is_caster: true,
    spellcasting_ability: 'cha',
    cantrips_known: 4,
    spells_known_at_1: 2,
    spell_slots_at_1: { 1: 2 },
    spell_list_at_1: ['Burning Hands', 'Charm Person', 'Chromatic Orb', 'Detect Magic', 'Feather Fall', 'Mage Armor', 'Magic Missile', 'Shield', 'Sleep', 'Witch Bolt'],
    cantrip_list: ['Blade Ward', 'Fire Bolt', 'Light', 'Mage Hand', 'Message', 'Minor Illusion', 'Prestidigitation', 'Ray of Frost', 'Shocking Grasp'],
  },
  warlock: {
    name: 'Warlock',
    description: 'Power drawn from a pact with an otherworldly entity.',
    playstyle: 'Reliable magic that recharges on short rests. Strong social skills.',
    hit_die: 8,
    hp_at_1: 8,
    armor_profs: ['Light armor'],
    weapon_profs: ['Simple weapons'],
    saving_throws: ['wis', 'cha'],
    skill_choices: { count: 2, from: ['Arcana', 'Deception', 'History', 'Intimidation', 'Investigation', 'Nature', 'Religion'] },
    subclass_at_1: {
      label: 'Otherworldly Patron',
      options: [
        { id: 'archfey', name: 'The Archfey', description: 'Fey magic: charm, fear, illusion. Connected to the courts of the Feywild.' },
        { id: 'fiend', name: 'The Fiend', description: 'Dark power: fire and necrotic. Gain temp HP when you kill enemies.' },
        { id: 'great_old_one', name: 'The Great Old One', description: 'Eldritch horror: telepathy, madness. The patron may not even know you exist.' },
      ],
    },
    features_at_1: [
      { name: 'Pact Magic', description: '1 spell slot at level 1, regains on short or long rest. Spells always cast at highest available slot.', recharge: 'short_rest', uses: 1 },
      { name: 'Eldritch Invocations', description: 'At level 2, gain 2 invocations that enhance your magic.' },
    ],
    equipment_options: [
      ['Light crossbow', '20 bolts', 'Leather armor', 'Arcane focus', 'Scholar\'s pack', '10 gp'],
      ['Simple weapon', 'Leather armor', 'Component pouch', 'Dungeoneer\'s pack', '10 gp'],
    ],
    is_caster: true,
    spellcasting_ability: 'cha',
    cantrips_known: 2,
    spells_known_at_1: 2,
    spell_slots_at_1: { 1: 1 },
    spell_list_at_1: ['Armor of Agathys', 'Arms of Hadar', 'Charm Person', 'Comprehend Languages', 'Expeditious Retreat', 'Hellish Rebuke', 'Hex', 'Illusory Script', 'Protection from Evil and Good', 'Unseen Servant', 'Witch Bolt'],
    cantrip_list: ['Blade Ward', 'Chill Touch', 'Eldritch Blast', 'Friends', 'Mage Hand', 'Minor Illusion', 'Poison Spray', 'Prestidigitation', 'True Strike'],
  },
  wizard: {
    name: 'Wizard',
    description: 'A scholar of the arcane, wielding magic learned through rigorous study.',
    playstyle: 'The deepest spell list in the game, prepared fresh each day. Fragile — stay at range.',
    hit_die: 6,
    hp_at_1: 6,
    armor_profs: [],
    weapon_profs: ['Daggers', 'Darts', 'Slings', 'Quarterstaffs', 'Light crossbows'],
    saving_throws: ['int', 'wis'],
    skill_choices: { count: 3, from: ['Arcana', 'History', 'Insight', 'Investigation', 'Medicine', 'Religion'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Spellcasting', description: 'Cast Wizard spells using INT. Prepare spells each long rest (level + INT mod) from your spellbook.' },
      { name: 'Ritual Adept', description: 'Cast any spell in your spellbook with the ritual tag as a ritual, without expending a slot.' },
      { name: 'Arcane Recovery', description: '1/long rest, after a short rest, recover spell slots totaling up to half your Wizard level (round up).' },
    ],
    equipment_options: [
      ['Quarterstaff', 'Component pouch', 'Spellbook', 'Scholar\'s pack', '10 gp'],
      ['Dagger', 'Arcane focus', 'Spellbook', 'Scholar\'s pack', '10 gp'],
    ],
    is_caster: true,
    spellcasting_ability: 'int',
    cantrips_known: 3,
    spells_known_at_1: 6,
    spell_slots_at_1: { 1: 2 },
    spell_list_at_1: ['Burning Hands', 'Charm Person', 'Detect Magic', 'Feather Fall', 'Mage Armor', 'Magic Missile', 'Shield', 'Sleep', 'Thunderwave'],
    cantrip_list: ['Fire Bolt', 'Light', 'Mage Hand', 'Message', 'Minor Illusion', 'Prestidigitation', 'Ray of Frost', 'Shocking Grasp'],
  },
}

export const BACKGROUNDS: Record<BackgroundId, BackgroundData> = {
  acolyte: {
    name: 'Acolyte',
    description: 'You have spent your life in service to a temple.',
    skills: ['Insight', 'Religion'],
    tools: ['Calligrapher\'s Supplies'],
    feat: 'Magic Initiate (Cleric)',
    asi: { primary: 'wis', secondary: 'int' },
    equipment: ['Holy symbol', 'Prayer book', '5 sticks of incense', 'Vestments', '15 gp'],
  },
  artisan: {
    name: 'Artisan',
    description: 'Trained in a craft guild, you know the value of quality work.',
    skills: ['Investigation', 'Persuasion'],
    tools: ['One artisan\'s tool of your choice'],
    feat: 'Crafter',
    asi: { primary: 'int', secondary: 'cha' },
    equipment: ['Artisan\'s tools', 'Letter of introduction', '15 gp'],
  },
  charlatan: {
    name: 'Charlatan',
    description: 'You have always had a knack for making people believe what you want.',
    skills: ['Deception', 'Sleight of Hand'],
    tools: ['Forgery Kit'],
    feat: 'Skilled',
    asi: { primary: 'cha', secondary: 'dex' },
    equipment: ['Fine clothes', 'Disguise kit', 'Con tools', '15 gp'],
  },
  criminal: {
    name: 'Criminal',
    description: 'You have a history with the wrong side of the law.',
    skills: ['Deception', 'Stealth'],
    tools: ['Thieves\' Tools'],
    feat: 'Alert',
    asi: { primary: 'dex', secondary: 'int' },
    equipment: ['Crowbar', 'Dark common clothes with hood', '15 gp'],
  },
  entertainer: {
    name: 'Entertainer',
    description: 'You thrive in front of an audience.',
    skills: ['Acrobatics', 'Performance'],
    tools: ['Musical Instrument'],
    feat: 'Musician',
    asi: { primary: 'cha', secondary: 'dex' },
    equipment: ['Musical instrument', 'Favor from an admirer', 'Costume', '15 gp'],
  },
  farmer: {
    name: 'Farmer',
    description: 'You come from a working background, tending land and animals.',
    skills: ['Animal Handling', 'Nature'],
    tools: ['Carpenter\'s Tools'],
    feat: 'Tough',
    asi: { primary: 'con', secondary: 'wis' },
    equipment: ['Sickle', 'Herbalism kit', 'Traveler\'s clothes', '30 gp'],
  },
  guard: {
    name: 'Guard',
    description: 'You served as a member of a town or city watch.',
    skills: ['Athletics', 'Perception'],
    tools: ['Gaming Set'],
    feat: 'Alert',
    asi: { primary: 'str', secondary: 'int' },
    equipment: ['Spear', 'Light crossbow', '20 bolts', 'Token of home city', '10 gp'],
  },
  guide: {
    name: 'Guide',
    description: 'You know the wilderness and have led others safely through it.',
    skills: ['Stealth', 'Survival'],
    tools: ['Cartographer\'s Tools'],
    feat: 'Magic Initiate (Druid)',
    asi: { primary: 'dex', secondary: 'wis' },
    equipment: ['Cartographer\'s tools', 'Traveler\'s clothes', 'Trophy from the wilds', '10 gp'],
  },
  hermit: {
    name: 'Hermit',
    description: 'You lived in seclusion — perhaps a monastery, or a cave in the wilderness.',
    skills: ['Medicine', 'Religion'],
    tools: ['Herbalism Kit'],
    feat: 'Magic Initiate (Druid)',
    asi: { primary: 'wis', secondary: 'con' },
    equipment: ['Scroll of parchment', 'Herbalism kit', 'Winter blanket', '5 gp'],
  },
  noble: {
    name: 'Noble',
    description: 'You were born into privilege and carry its weight.',
    skills: ['History', 'Persuasion'],
    tools: ['Gaming Set'],
    feat: 'Skilled',
    asi: { primary: 'cha', secondary: 'int' },
    equipment: ['Fine clothes', 'Signet ring', 'Scroll of pedigree', '25 gp'],
  },
  sage: {
    name: 'Sage',
    description: 'You spent years studying in libraries and academies.',
    skills: ['Arcana', 'History'],
    tools: ['Calligrapher\'s Supplies'],
    feat: 'Magic Initiate (Wizard)',
    asi: { primary: 'int', secondary: 'wis' },
    equipment: ['Knife', 'Letter from dead colleague', 'Common clothes', '10 gp'],
  },
  sailor: {
    name: 'Sailor',
    description: 'You sailed the seas and learned to work as part of a crew.',
    skills: ['Athletics', 'Perception'],
    tools: ['Navigator\'s Tools'],
    feat: 'Tavern Brawler',
    asi: { primary: 'str', secondary: 'dex' },
    equipment: ['Belaying pin', '50 ft of silk rope', 'Lucky charm', '10 gp'],
  },
  soldier: {
    name: 'Soldier',
    description: 'You trained and fought as part of an army.',
    skills: ['Athletics', 'Intimidation'],
    tools: ['Gaming Set'],
    feat: 'Savage Attacker',
    asi: { primary: 'str', secondary: 'con' },
    equipment: ['Insignia of rank', 'Trophy from fallen enemy', 'Common clothes', '10 gp'],
  },
  wayfarer: {
    name: 'Wayfarer',
    description: 'You have traveled widely and learned to live by your wits.',
    skills: ['Insight', 'Stealth'],
    tools: ['Thieves\' Tools'],
    feat: 'Lucky',
    asi: { primary: 'dex', secondary: 'wis' },
    equipment: ['Bedroll', 'Gaming set', 'Traveler\'s clothes', '16 gp'],
  },
}
