import type { SpeciesData, ClassData, BackgroundData, SpeciesId, ClassId, BackgroundId } from './srd-types'

export const ALL_SKILLS = [
  'Acrobaties', 'Dressage', 'Arcanes', 'Athlétisme', 'Tromperie', 'Histoire',
  'Perspicacité', 'Intimidation', 'Investigation', 'Médecine', 'Nature', 'Perception',
  'Représentation', 'Persuasion', 'Religion', 'Escamotage', 'Discrétion', 'Survie',
]

export const SPECIES: Record<SpeciesId, SpeciesData> = {
  human: {
    name: 'Humain',
    description: 'Adaptable et ambitieux. Gagnez une compétence supplémentaire, l\'Inspiration héroïque après chaque repos long, et un don d\'origine.',
    speed: 30,
    size: 'Moyenne',
    traits: [
      { name: 'Inspiration héroïque', description: 'Gagnez l\'Inspiration héroïque à la fin d\'un repos long.' },
      { name: 'Habile', description: 'Gagnez la maîtrise d\'une compétence de votre choix.' },
      { name: 'Polyvalent', description: 'Gagnez le don d\'origine Talentueux ou Alerte.' },
    ],
    subraces: null,
  },
  elf: {
    name: 'Elfe',
    description: 'Gracieux et longévif, doté de sens aiguisés et d\'un héritage féerique.',
    speed: 30,
    size: 'Moyenne',
    traits: [
      { name: 'Vision dans le noir', description: '18 m.' },
      { name: 'Ascendance féerique', description: 'Avantage aux jets de sauvegarde contre être Charmé. Immunisé au sommeil magique.' },
      { name: 'Sens aiguisés', description: 'Maîtrise de la Perception.' },
      { name: 'Transe', description: '4 heures de méditation remplacent 8 heures de sommeil.' },
    ],
    subraces: {
      high_elf: { name: 'Haut-Elfe', extra: 'Connaît un sort mineur de Magicien (INT). Maîtrise de l\'épée longue, de l\'épée courte, de l\'arc court, de l\'arc long.' },
      wood_elf: { name: 'Elfe des bois', extra: 'Vitesse 10,5 m. Masque de la nature : se cache lorsque légèrement dissimulé par la nature. Maîtrise de l\'épée longue, de l\'épée courte, de l\'arc court, de l\'arc long.' },
      drow: { name: 'Drow', extra: 'Vision dans le noir 36 m. Sensibilité à la lumière du soleil. Connaît le sort mineur Lumières dansantes. Maîtrise de la rapière, de l\'épée courte, de l\'arbalète de poing.' },
    },
  },
  dwarf: {
    name: 'Nain',
    description: 'Robuste et résistant, avec des liens ancestraux avec la pierre et l\'artisanat.',
    speed: 30,
    size: 'Moyenne',
    traits: [
      { name: 'Vision dans le noir', description: '36 m.' },
      { name: 'Résilience naine', description: 'Résistance aux dégâts de poison. Avantage aux jets de sauvegarde contre le poison.' },
      { name: 'Sens de la pierre', description: 'Sens sismique 18 m pendant 10 minutes, utilisable BM fois par repos long.' },
      { name: 'Endurance naine', description: '+1 PV par niveau (Nain des collines uniquement).' },
    ],
    subraces: {
      hill_dwarf: { name: 'Nain des collines', extra: 'Endurance naine : +1 PV par niveau.' },
      mountain_dwarf: { name: 'Nain des montagnes', extra: 'Maîtrise des armures légères et intermédiaires.' },
    },
  },
  halfling: {
    name: 'Halfelin',
    description: 'Petit mais chanceux et étonnamment intrépide.',
    speed: 30,
    size: 'Petite',
    traits: [
      { name: 'Chanceux', description: 'Quand vous obtenez un 1 sur un test de d20, relancez le dé et utilisez le nouveau résultat.' },
      { name: 'Brave', description: 'Avantage aux jets de sauvegarde contre être Terrifié.' },
      { name: 'Agilité halfeline', description: 'Peut traverser la case de toute créature plus grande que vous.' },
    ],
    subraces: {
      lightfoot: { name: 'Pieds-légers', extra: 'Discrétion naturelle : peut se cacher derrière des créatures plus grandes que vous.' },
      stout: { name: 'Robuste', extra: 'Résilience robuste : avantage aux jets de sauvegarde contre le poison, résistance aux dégâts de poison.' },
    },
  },
  gnome: {
    name: 'Gnome',
    description: 'Curieux, inventif, et doué de magie.',
    speed: 30,
    size: 'Petite',
    traits: [
      { name: 'Vision dans le noir', description: '18 m.' },
      { name: 'Ruse gnome', description: 'Avantage aux jets de sauvegarde d\'INT, de SAG et de CHA contre la magie.' },
    ],
    subraces: {
      forest_gnome: { name: 'Gnome des forêts', extra: 'Connaît le sort mineur Illusion mineure. Parle avec les petites bêtes.' },
      rock_gnome: { name: 'Gnome des rochers', extra: 'Maîtrise de l\'Histoire et des outils d\'artisan horloger. Peut fabriquer de petits mécanismes d\'horlogerie.' },
    },
  },
  half_elf: {
    name: 'Demi-Elfe',
    description: 'Mi-humain, mi-elfe — appartenant aux deux mondes et à aucun.',
    speed: 30,
    size: 'Moyenne',
    traits: [
      { name: 'Vision dans le noir', description: '18 m.' },
      { name: 'Ascendance féerique', description: 'Avantage aux jets de sauvegarde contre être Charmé. Immunisé au sommeil magique.' },
      { name: 'Polyvalence', description: 'Gagnez la maîtrise de deux compétences de votre choix.' },
    ],
    subraces: null,
  },
  half_orc: {
    name: 'Demi-Orque',
    description: 'Robuste, puissant, et bâti pour survivre.',
    speed: 30,
    size: 'Moyenne',
    traits: [
      { name: 'Vision dans le noir', description: '18 m.' },
      { name: 'Endurance implacable', description: 'Lorsque vous tombez à 0 PV, tombez à 1 PV à la place. 1 fois par repos long.' },
      { name: 'Attaques sauvages', description: 'Lors d\'un coup critique avec une arme de mêlée, lancez un dé de dégâts d\'arme supplémentaire.' },
      { name: 'Montée d\'adrénaline', description: 'Foncez en tant qu\'action bonus, gagnez des PV temporaires égaux à BM. BM fois par repos long.' },
    ],
    subraces: null,
  },
  tiefling: {
    name: 'Tieffelin',
    description: 'Un héritage infernal vous marque — mais votre destin vous appartient.',
    speed: 30,
    size: 'Moyenne',
    traits: [
      { name: 'Vision dans le noir', description: '18 m.' },
      { name: 'Résistance infernale', description: 'Résistance aux dégâts de feu.' },
      { name: 'Héritage infernal', description: 'Connaît le sort mineur Thaumaturgie. Au niveau 3 : lance Réprimande infernale 1 fois par repos long. Au niveau 5 : lance Ténèbres 1 fois par repos long.' },
    ],
    subraces: null,
  },
  dragonborn: {
    name: 'Drakéide',
    description: 'Le pouvoir draconique coule dans votre sang.',
    speed: 30,
    size: 'Moyenne',
    traits: [
      { name: 'Vision dans le noir', description: '18 m.' },
      { name: 'Souffle', description: 'Exhalez une énergie destructrice (type de dégâts selon l\'ascendance). BM fois par repos long. DD = 8 + mod. de CON + BM.' },
      { name: 'Ascendance draconique', description: 'Choisissez un type de dragon : détermine le type de dégâts du souffle et la résistance.' },
      { name: 'Résistance aux dégâts', description: 'Résistance au type de dégâts de votre ascendance.' },
    ],
    subraces: null,
  },
}

export const CLASSES: Record<ClassId, ClassData> = {
  barbarian: {
    name: 'Barbare',
    description: 'Un guerrier féroce alimenté par une rage primale.',
    playstyle: 'Foncez au corps-à-corps, encaissez les dégâts, frappez plus fort à mesure que le combat dure.',
    hit_die: 12,
    hp_at_1: 12,
    armor_profs: ['Armure légère', 'Armure intermédiaire', 'Boucliers'],
    weapon_profs: ['Armes simples', 'Armes de guerre'],
    saving_throws: ['str', 'con'],
    skill_choices: { count: 2, from: ['Dressage', 'Athlétisme', 'Intimidation', 'Nature', 'Perception', 'Survie'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Rage', description: 'Action bonus : entrez en rage pendant 1 minute — avantage aux tests de FOR/jets de sauvegarde de FOR, dégâts de mêlée supplémentaires, résistance aux dégâts contondants/perforants/tranchants. 2 utilisations, se recharge lors d\'un repos long.', recharge: 'long_rest', uses: 2 },
      { name: 'Défense sans armure', description: 'Sans armure, CA = 10 + mod. de DEX + mod. de CON.' },
      { name: 'Maîtrise des armes', description: 'Appliquez la propriété de maîtrise de deux types d\'armes dans lesquelles vous êtes compétent.' },
    ],
    equipment_options: [
      ['Hache d\'armes', '4 hachettes', 'Sac d\'explorateur', '10 po'],
      ['Une arme de mêlée de guerre au choix', 'Bouclier', '4 javelines', 'Sac d\'explorateur', '10 po'],
    ],
    is_caster: false,
  },
  bard: {
    name: 'Barde',
    description: 'Un artiste dont l\'art recèle une magie véritable.',
    playstyle: 'Soutien polyvalent et touche-à-tout — renforcez vos alliés, affaiblissez vos ennemis, comblez n\'importe quelle lacune.',
    hit_die: 8,
    hp_at_1: 8,
    armor_profs: ['Armure légère'],
    weapon_profs: ['Armes simples', 'Arbalètes de poing', 'Épées longues', 'Rapières', 'Épées courtes'],
    saving_throws: ['dex', 'cha'],
    skill_choices: { count: 3, from: ['Acrobaties', 'Dressage', 'Arcanes', 'Athlétisme', 'Tromperie', 'Histoire', 'Perspicacité', 'Intimidation', 'Investigation', 'Médecine', 'Nature', 'Perception', 'Représentation', 'Persuasion', 'Religion', 'Escamotage', 'Discrétion', 'Survie'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Inspiration bardique', description: 'Action bonus : donnez à un allié un d6 qu\'il peut ajouter à un test de caractéristique, un jet d\'attaque ou un jet de sauvegarde. Utilisations = mod. de CHA (min. 1), se recharge lors d\'un repos long.', recharge: 'long_rest' },
      { name: 'Incantation', description: 'Lancez des sorts de Barde en utilisant le CHA.' },
    ],
    equipment_options: [
      ['Armure de cuir', 'Rapière', 'Instrument de musique', 'Sac de troubadour', '10 po'],
      ['Armure de cuir', 'Arme simple', 'Instrument de musique', 'Sac de diplomate', '10 po'],
    ],
    is_caster: true,
    spellcasting_ability: 'cha',
    cantrips_known: 2,
    spells_known_at_1: 4,
    spell_slots_at_1: { 1: 2 },
    spell_list_at_1: ['Charme-personne', 'Compréhension des langues', 'Soins', 'Détection de la magie', 'Image déguisée', 'Feu de Faérie', 'Chute de plumes', 'Mot de guérison', 'Héroïsme', 'Sommeil', 'Fou rire de Tasha', 'Onde de tonnerre'],
    cantrip_list: ['Lumières dansantes', 'Ami-ami', 'Main du mage', 'Réparation', 'Message', 'Illusion mineure', 'Prestidigitation', 'Frappe assurée', 'Moquerie cruelle'],
  },
  cleric: {
    name: 'Clerc',
    description: 'Un vecteur de puissance divine, guérisseur et guerrier à la fois.',
    playstyle: 'Maintenez le groupe en vie tout en tenant votre rang au corps-à-corps.',
    hit_die: 8,
    hp_at_1: 8,
    armor_profs: ['Armure légère', 'Armure intermédiaire', 'Boucliers'],
    weapon_profs: ['Armes simples'],
    saving_throws: ['wis', 'cha'],
    skill_choices: { count: 2, from: ['Histoire', 'Perspicacité', 'Médecine', 'Persuasion', 'Religion'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Incantation', description: 'Lancez des sorts de Clerc en utilisant la SAG. Préparez vos sorts après chaque repos long (niveau + mod. de SAG).' },
      { name: 'Ordre divin', description: 'Choisissez Protecteur (maîtrise des armes de guerre et des armures lourdes) ou Thaumaturge (sort mineur supplémentaire, tests de Religion renforcés).' },
    ],
    equipment_options: [
      ['Chemise de mailles', 'Bouclier', 'Masse d\'armes', 'Symbole sacré', 'Sac de prêtre', '10 po'],
      ['Armure de cuir', 'Masse d\'armes', 'Symbole sacré', 'Sac de prêtre', '15 po'],
    ],
    is_caster: true,
    spellcasting_ability: 'wis',
    cantrips_known: 3,
    spells_known_at_1: 4,
    spell_slots_at_1: { 1: 2 },
    spell_list_at_1: ['Bénédiction', 'Soins', 'Ordre', 'Détection du mal et du bien', 'Trait guide', 'Mot de guérison', 'Blessures', 'Protection contre le mal et le bien', 'Sanctuaire', 'Bouclier de la foi'],
    cantrip_list: ['Assistance', 'Lumière', 'Réparation', 'Résistance', 'Flamme sacrée', 'Stabilisation', 'Thaumaturgie'],
  },
  druid: {
    name: 'Druide',
    description: 'Un gardien du monde naturel capable de prendre forme animale.',
    playstyle: 'Lanceur de sorts polyvalent, puissant en extérieur, peut se changer en bête en cas de besoin.',
    hit_die: 8,
    hp_at_1: 8,
    armor_profs: ['Armure légère', 'Armure intermédiaire', 'Boucliers (non métalliques)'],
    weapon_profs: ['Gourdins', 'Dagues', 'Fléchettes', 'Javelines', 'Masses d\'armes', 'Bâtons', 'Cimeterres', 'Faucilles', 'Frondes', 'Lances'],
    saving_throws: ['int', 'wis'],
    skill_choices: { count: 2, from: ['Arcanes', 'Dressage', 'Perspicacité', 'Médecine', 'Nature', 'Perception', 'Religion', 'Survie'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Incantation', description: 'Lancez des sorts de Druide en utilisant la SAG. Préparez vos sorts après chaque repos long (niveau + mod. de SAG).' },
      { name: 'Druidique', description: 'Connaît le langage secret des druides.' },
      { name: 'Ordre primitif', description: 'Choisissez Magicien (sort mineur supplémentaire, tests de Nature/Religion renforcés) ou Gardien (maîtrise des armes de guerre et des armures intermédiaires).' },
    ],
    equipment_options: [
      ['Armure de cuir', 'Faucille', 'Focaliseur druidique', 'Sac d\'explorateur', '10 po'],
      ['Armure de peaux', 'Bâton', 'Focaliseur druidique', 'Sac d\'explorateur', '10 po'],
    ],
    is_caster: true,
    spellcasting_ability: 'wis',
    cantrips_known: 2,
    spells_known_at_1: 4,
    spell_slots_at_1: { 1: 2 },
    spell_list_at_1: ['Amitié avec les animaux', 'Charme-personne', 'Soins', 'Enchevêtrement', 'Feu de Faérie', 'Nuage de brouillard', 'Mot de guérison', 'Communication avec les animaux', 'Onde de tonnerre'],
    cantrip_list: ['Druidisme', 'Assistance', 'Réparation', 'Jet de poison', 'Flamme créée', 'Résistance', 'Trique noueuse'],
  },
  fighter: {
    name: 'Guerrier',
    description: 'Maître des armes et des armures. La classe martiale la plus polyvalente.',
    playstyle: 'Rapprochez-vous, encaissez les coups, rendez-les.',
    hit_die: 10,
    hp_at_1: 10,
    armor_profs: ['Armure légère', 'Armure intermédiaire', 'Armure lourde', 'Boucliers'],
    weapon_profs: ['Armes simples', 'Armes de guerre'],
    saving_throws: ['str', 'con'],
    skill_choices: { count: 2, from: ['Acrobaties', 'Dressage', 'Athlétisme', 'Histoire', 'Perspicacité', 'Intimidation', 'Perception', 'Survie'] },
    subclass_at_1: {
      label: 'Style de combat',
      options: [
        { id: 'archery', name: 'Archerie', description: 'Bonus de +2 aux jets d\'attaque avec les armes à distance.' },
        { id: 'defense', name: 'Défense', description: '+1 CA en portant une armure.' },
        { id: 'dueling', name: 'Duel', description: '+2 dégâts en maniant une arme de mêlée à une main sans autre arme.' },
        { id: 'great_weapon', name: 'Combat à deux mains', description: 'Relancez les 1 et les 2 sur les dés de dégâts d\'arme lors de l\'utilisation d\'une arme à deux mains.' },
        { id: 'protection', name: 'Protection', description: 'Quand une créature que vous voyez attaque une cible près de vous, imposez le désavantage (utilise une réaction + un bouclier).' },
        { id: 'two_weapon', name: 'Combat à deux armes', description: 'Ajoutez le modificateur de caractéristique aux dégâts de l\'attaque avec l\'arme de la main secondaire.' },
      ],
    },
    features_at_1: [
      { name: 'Second souffle', description: 'Action bonus : récupérez 1d10 + niveau de Guerrier PV. Se recharge lors d\'un repos court.', recharge: 'short_rest', uses: 1 },
    ],
    equipment_options: [
      ['Cotte de mailles', 'Épée longue', 'Bouclier', '4 javelines', 'Sac d\'explorateur', '10 po'],
      ['Armure de cuir', 'Arc long', '20 flèches', '2 épées courtes', 'Sac d\'explorateur', '10 po'],
    ],
    is_caster: false,
  },
  monk: {
    name: 'Moine',
    description: 'Un artiste martial qui canalise sa discipline intérieure en une prouesse martiale surnaturelle.',
    playstyle: 'Frappeur rapide et mobile — frappez plusieurs fois, esquivez tout, aucune armure nécessaire.',
    hit_die: 8,
    hp_at_1: 8,
    armor_profs: [],
    weapon_profs: ['Armes simples', 'Épées courtes'],
    saving_throws: ['str', 'dex'],
    skill_choices: { count: 2, from: ['Acrobaties', 'Athlétisme', 'Histoire', 'Perspicacité', 'Religion', 'Discrétion'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Arts martiaux', description: 'Les attaques à mains nues et les armes de moine utilisent la DEX si elle est supérieure, infligent 1d6, et les attaques à mains nues peuvent être une action bonus.' },
      { name: 'Défense sans armure', description: 'Sans armure ni bouclier, CA = 10 + mod. de DEX + mod. de SAG.' },
    ],
    equipment_options: [
      ['Lance', '5 fléchettes', 'Sac d\'explorateur'],
      ['Une arme simple au choix', '5 fléchettes', 'Sac d\'explorateur'],
    ],
    is_caster: false,
  },
  paladin: {
    name: 'Paladin',
    description: 'Un guerrier lié par un serment sacré, soutenu par la magie divine.',
    playstyle: 'Tank de première ligne avec soins explosifs et pouvoir de châtiment.',
    hit_die: 10,
    hp_at_1: 10,
    armor_profs: ['Armure légère', 'Armure intermédiaire', 'Armure lourde', 'Boucliers'],
    weapon_profs: ['Armes simples', 'Armes de guerre'],
    saving_throws: ['wis', 'cha'],
    skill_choices: { count: 2, from: ['Athlétisme', 'Perspicacité', 'Intimidation', 'Médecine', 'Persuasion', 'Religion'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Imposition des mains', description: 'Une réserve de soins égale à 5 × niveau (5 au niveau 1), utilisable en tant qu\'action pour restaurer des PV ou soigner une maladie/un poison. Se recharge lors d\'un repos long.', recharge: 'long_rest' },
      { name: 'Maîtrise des armes', description: 'Appliquez la propriété de maîtrise de deux types d\'armes dans lesquelles vous êtes compétent.' },
    ],
    equipment_options: [
      ['Cotte de mailles', 'Épée longue', 'Bouclier', '6 javelines', 'Symbole sacré', '10 po'],
      ['Armure de cuir', 'Arme simple', 'Symbole sacré', 'Sac de prêtre', '10 po'],
    ],
    is_caster: false,
  },
  ranger: {
    name: 'Rôdeur',
    description: 'Un chasseur et éclaireur des contrées sauvages, aussi mortel à distance qu\'au corps-à-corps.',
    playstyle: 'Escarmoucheur à distance avec de solides compétences de pistage et de survie.',
    hit_die: 10,
    hp_at_1: 10,
    armor_profs: ['Armure légère', 'Armure intermédiaire', 'Boucliers'],
    weapon_profs: ['Armes simples', 'Armes de guerre'],
    saving_throws: ['str', 'dex'],
    skill_choices: { count: 3, from: ['Dressage', 'Athlétisme', 'Perspicacité', 'Investigation', 'Nature', 'Perception', 'Discrétion', 'Survie'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Ennemi juré', description: 'Connaît un sort de la liste de Druide (selon le don d\'origine), et bénéficie de l\'avantage aux tests de Survie pour traquer votre proie.' },
      { name: 'Maîtrise des armes', description: 'Appliquez la propriété de maîtrise de deux types d\'armes dans lesquelles vous êtes compétent.' },
    ],
    equipment_options: [
      ['Armure de cuir', 'Arc long', '20 flèches', '2 épées courtes', 'Sac d\'explorateur', '10 po'],
      ['Armure d\'écailles', 'Épée courte', 'Arc court', '20 flèches', 'Sac d\'explorateur', '10 po'],
    ],
    is_caster: false,
  },
  rogue: {
    name: 'Roublard',
    description: 'Un spécialiste de la discrétion, des frappes précises, et de l\'art de s\'en tirer.',
    playstyle: 'Frappeur axé sur les compétences — éclairez le chemin, crochetez les serrures, et abattez une cible à la fois.',
    hit_die: 8,
    hp_at_1: 8,
    armor_profs: ['Armure légère'],
    weapon_profs: ['Armes simples', 'Arbalètes de poing', 'Épées longues', 'Rapières', 'Épées courtes'],
    saving_throws: ['dex', 'int'],
    skill_choices: { count: 4, from: ['Acrobaties', 'Athlétisme', 'Tromperie', 'Perspicacité', 'Intimidation', 'Investigation', 'Perception', 'Représentation', 'Persuasion', 'Escamotage', 'Discrétion'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Expertise', description: 'Doublez le bonus de maîtrise sur deux compétences maîtrisées (ou une compétence + les outils de voleur).' },
      { name: 'Attaque sournoise', description: 'Une fois par tour, infligez 1d6 dégâts supplémentaires lors d\'une attaque avec avantage ou avec un allié adjacent à la cible.' },
      { name: 'Argot des voleurs', description: 'Connaît l\'argot secret des roublards et ses signes cachés.' },
      { name: 'Maîtrise des armes', description: 'Appliquez la propriété de maîtrise de deux types d\'armes dans lesquelles vous êtes compétent.' },
    ],
    equipment_options: [
      ['Armure de cuir', 'Rapière', 'Arc court', '20 flèches', 'Sac de cambrioleur', 'Outils de voleur', '10 po'],
      ['Armure de cuir', '2 dagues', 'Épée courte', 'Sac de cambrioleur', 'Outils de voleur', '10 po'],
    ],
    is_caster: false,
  },
  sorcerer: {
    name: 'Ensorceleur',
    description: 'Un lanceur de sorts dont la magie est innée, née du sang ou d\'un événement étrange.',
    playstyle: 'Une liste de sorts restreinte mais puissante, remodelée à la volée grâce à la magie innée.',
    hit_die: 6,
    hp_at_1: 6,
    armor_profs: [],
    weapon_profs: ['Dagues', 'Fléchettes', 'Frondes', 'Bâtons', 'Arbalètes légères'],
    saving_throws: ['con', 'cha'],
    skill_choices: { count: 2, from: ['Arcanes', 'Tromperie', 'Perspicacité', 'Intimidation', 'Persuasion', 'Religion'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Incantation', description: 'Lancez des sorts d\'Ensorceleur en utilisant le CHA.' },
      { name: 'Magie innée', description: 'Action bonus : pendant 1 minute, votre DD de sauvegarde de sorts et votre bonus d\'attaque de sorts gagnent chacun +1, et tout sort lancé avec un emplacement de niveau 1 n\'utilise aucun emplacement la première fois à chaque tour. 2 utilisations, se recharge lors d\'un repos long.', recharge: 'long_rest', uses: 2 },
    ],
    equipment_options: [
      ['Arbalète légère', '20 carreaux', 'Focaliseur arcanique', 'Sac d\'aventurier des souterrains', '10 po'],
      ['Arme simple', 'Focaliseur arcanique', 'Sac d\'aventurier des souterrains', '10 po'],
    ],
    is_caster: true,
    spellcasting_ability: 'cha',
    cantrips_known: 4,
    spells_known_at_1: 2,
    spell_slots_at_1: { 1: 2 },
    spell_list_at_1: ['Mains brûlantes', 'Charme-personne', 'Orbe chromatique', 'Détection de la magie', 'Chute de plumes', 'Armure du mage', 'Projectile magique', 'Bouclier', 'Sommeil', 'Trait de sorcière'],
    cantrip_list: ['Garde-lame', 'Trait de feu', 'Lumière', 'Main du mage', 'Message', 'Illusion mineure', 'Prestidigitation', 'Rayon de givre', 'Contact électrique'],
  },
  warlock: {
    name: 'Occultiste',
    description: 'Un pouvoir tiré d\'un pacte avec une entité d\'un autre monde.',
    playstyle: 'Une magie fiable qui se recharge lors des repos courts. Solides compétences sociales.',
    hit_die: 8,
    hp_at_1: 8,
    armor_profs: ['Armure légère'],
    weapon_profs: ['Armes simples'],
    saving_throws: ['wis', 'cha'],
    skill_choices: { count: 2, from: ['Arcanes', 'Tromperie', 'Histoire', 'Intimidation', 'Investigation', 'Nature', 'Religion'] },
    subclass_at_1: {
      label: 'Protecteur extraplanaire',
      options: [
        { id: 'archfey', name: 'L\'Archifée', description: 'Magie féerique : charme, peur, illusion. Liée aux cours du Royaume des Fées.' },
        { id: 'fiend', name: 'Le Fiélon', description: 'Pouvoir obscur : feu et nécrotique. Gagnez des PV temporaires quand vous tuez des ennemis.' },
        { id: 'great_old_one', name: 'Le Grand Ancien', description: 'Horreur ésotérique : télépathie, folie. Le protecteur pourrait même ignorer votre existence.' },
      ],
    },
    features_at_1: [
      { name: 'Magie de pacte', description: '1 emplacement de sort au niveau 1, récupéré lors d\'un repos court ou long. Les sorts sont toujours lancés au niveau d\'emplacement le plus élevé disponible.', recharge: 'short_rest', uses: 1 },
      { name: 'Invocations occultes', description: 'Au niveau 2, gagnez 2 invocations qui améliorent votre magie.' },
    ],
    equipment_options: [
      ['Arbalète légère', '20 carreaux', 'Armure de cuir', 'Focaliseur arcanique', 'Sac d\'érudit', '10 po'],
      ['Arme simple', 'Armure de cuir', 'Sac de composants', 'Sac d\'aventurier des souterrains', '10 po'],
    ],
    is_caster: true,
    spellcasting_ability: 'cha',
    cantrips_known: 2,
    spells_known_at_1: 2,
    spell_slots_at_1: { 1: 1 },
    spell_list_at_1: ['Armure d\'Agathys', 'Bras de Hadar', 'Charme-personne', 'Compréhension des langues', 'Retraite rapide', 'Réprimande infernale', 'Envoûtement', 'Écriture illusoire', 'Protection contre le mal et le bien', 'Serviteur invisible', 'Trait de sorcière'],
    cantrip_list: ['Garde-lame', 'Contact glacial', 'Décharge occulte', 'Ami-ami', 'Main du mage', 'Illusion mineure', 'Jet de poison', 'Prestidigitation', 'Frappe assurée'],
  },
  wizard: {
    name: 'Magicien',
    description: 'Un érudit de l\'arcane, maniant une magie apprise par une étude rigoureuse.',
    playstyle: 'La liste de sorts la plus vaste du jeu, préparée chaque jour. Fragile — restez à distance.',
    hit_die: 6,
    hp_at_1: 6,
    armor_profs: [],
    weapon_profs: ['Dagues', 'Fléchettes', 'Frondes', 'Bâtons', 'Arbalètes légères'],
    saving_throws: ['int', 'wis'],
    skill_choices: { count: 3, from: ['Arcanes', 'Histoire', 'Perspicacité', 'Investigation', 'Médecine', 'Religion'] },
    subclass_at_1: null,
    features_at_1: [
      { name: 'Incantation', description: 'Lancez des sorts de Magicien en utilisant l\'INT. Préparez vos sorts après chaque repos long (niveau + mod. d\'INT) depuis votre grimoire.' },
      { name: 'Adepte des rituels', description: 'Lancez tout sort de votre grimoire portant la mention rituel en tant que rituel, sans dépenser d\'emplacement.' },
      { name: 'Récupération arcanique', description: '1 fois par repos long, après un repos court, récupérez des emplacements de sorts totalisant jusqu\'à la moitié de votre niveau de Magicien (arrondi au supérieur).' },
    ],
    equipment_options: [
      ['Bâton', 'Sac de composants', 'Grimoire', 'Sac d\'érudit', '10 po'],
      ['Dague', 'Focaliseur arcanique', 'Grimoire', 'Sac d\'érudit', '10 po'],
    ],
    is_caster: true,
    spellcasting_ability: 'int',
    cantrips_known: 3,
    spells_known_at_1: 6,
    spell_slots_at_1: { 1: 2 },
    spell_list_at_1: ['Mains brûlantes', 'Charme-personne', 'Détection de la magie', 'Chute de plumes', 'Armure du mage', 'Projectile magique', 'Bouclier', 'Sommeil', 'Onde de tonnerre'],
    cantrip_list: ['Trait de feu', 'Lumière', 'Main du mage', 'Message', 'Illusion mineure', 'Prestidigitation', 'Rayon de givre', 'Contact électrique'],
  },
}

export const BACKGROUNDS: Record<BackgroundId, BackgroundData> = {
  acolyte: {
    name: 'Acolyte',
    description: 'Vous avez passé votre vie au service d\'un temple.',
    skills: ['Perspicacité', 'Religion'],
    tools: ['Matériel de calligraphie'],
    feat: 'Éveil magique (Clerc)',
    asi: { primary: 'wis', secondary: 'int' },
    equipment: ['Symbole sacré', 'Livre de prières', '5 bâtons d\'encens', 'Vêtements liturgiques', '15 po'],
  },
  artisan: {
    name: 'Artisan',
    description: 'Formé au sein d\'une guilde artisanale, vous connaissez la valeur du travail bien fait.',
    skills: ['Investigation', 'Persuasion'],
    tools: ['Un outil d\'artisan de votre choix'],
    feat: 'Fabricant',
    asi: { primary: 'int', secondary: 'cha' },
    equipment: ['Outils d\'artisan', 'Lettre d\'introduction', '15 po'],
  },
  charlatan: {
    name: 'Charlatan',
    description: 'Vous avez toujours eu le don de faire croire aux gens ce que vous vouliez.',
    skills: ['Tromperie', 'Escamotage'],
    tools: ['Kit de faussaire'],
    feat: 'Talentueux',
    asi: { primary: 'cha', secondary: 'dex' },
    equipment: ['Habits fins', 'Kit de déguisement', 'Outils d\'arnaque', '15 po'],
  },
  criminal: {
    name: 'Criminel',
    description: 'Vous avez un passé lié au mauvais côté de la loi.',
    skills: ['Tromperie', 'Discrétion'],
    tools: ['Outils de voleur'],
    feat: 'Alerte',
    asi: { primary: 'dex', secondary: 'int' },
    equipment: ['Pied-de-biche', 'Habits sombres et discrets avec capuche', '15 po'],
  },
  entertainer: {
    name: 'Artiste',
    description: 'Vous vous épanouissez devant un public.',
    skills: ['Acrobaties', 'Représentation'],
    tools: ['Instrument de musique'],
    feat: 'Musicien',
    asi: { primary: 'cha', secondary: 'dex' },
    equipment: ['Instrument de musique', 'Faveur d\'un admirateur', 'Costume', '15 po'],
  },
  farmer: {
    name: 'Fermier',
    description: 'Vous venez d\'un milieu modeste, à cultiver la terre et élever des animaux.',
    skills: ['Dressage', 'Nature'],
    tools: ['Outils de charpentier'],
    feat: 'Robuste',
    asi: { primary: 'con', secondary: 'wis' },
    equipment: ['Faucille', 'Kit d\'herboriste', 'Vêtements de voyage', '30 po'],
  },
  guard: {
    name: 'Garde',
    description: 'Vous avez servi comme membre de la garde d\'une ville.',
    skills: ['Athlétisme', 'Perception'],
    tools: ['Jeu de société'],
    feat: 'Alerte',
    asi: { primary: 'str', secondary: 'int' },
    equipment: ['Lance', 'Arbalète légère', '20 carreaux', 'Symbole de votre ville natale', '10 po'],
  },
  guide: {
    name: 'Guide',
    description: 'Vous connaissez la nature sauvage et avez guidé d\'autres personnes en sécurité à travers elle.',
    skills: ['Discrétion', 'Survie'],
    tools: ['Outils de cartographe'],
    feat: 'Éveil magique (Druide)',
    asi: { primary: 'dex', secondary: 'wis' },
    equipment: ['Outils de cartographe', 'Vêtements de voyage', 'Trophée pris dans la nature sauvage', '10 po'],
  },
  hermit: {
    name: 'Ermite',
    description: 'Vous avez vécu reclus — peut-être dans un monastère, ou une grotte isolée.',
    skills: ['Médecine', 'Religion'],
    tools: ['Kit d\'herboriste'],
    feat: 'Éveil magique (Druide)',
    asi: { primary: 'wis', secondary: 'con' },
    equipment: ['Rouleau de parchemin', 'Kit d\'herboriste', 'Couverture d\'hiver', '5 po'],
  },
  noble: {
    name: 'Noble',
    description: 'Vous êtes né dans le privilège et en portez le poids.',
    skills: ['Histoire', 'Persuasion'],
    tools: ['Jeu de société'],
    feat: 'Talentueux',
    asi: { primary: 'cha', secondary: 'int' },
    equipment: ['Habits fins', 'Chevalière', 'Parchemin généalogique', '25 po'],
  },
  sage: {
    name: 'Sage',
    description: 'Vous avez passé des années à étudier dans des bibliothèques et des académies.',
    skills: ['Arcanes', 'Histoire'],
    tools: ['Matériel de calligraphie'],
    feat: 'Éveil magique (Magicien)',
    asi: { primary: 'int', secondary: 'wis' },
    equipment: ['Couteau', 'Lettre d\'un collègue décédé', 'Habits ordinaires', '10 po'],
  },
  sailor: {
    name: 'Marin',
    description: 'Vous avez navigué sur les mers et appris à travailler au sein d\'un équipage.',
    skills: ['Athlétisme', 'Perception'],
    tools: ['Outils de navigateur'],
    feat: 'Bagarreur de taverne',
    asi: { primary: 'str', secondary: 'dex' },
    equipment: ['Cabillot', '15 m de corde de soie', 'Porte-bonheur', '10 po'],
  },
  soldier: {
    name: 'Soldat',
    description: 'Vous vous êtes entraîné et avez combattu au sein d\'une armée.',
    skills: ['Athlétisme', 'Intimidation'],
    tools: ['Jeu de société'],
    feat: 'Attaquant féroce',
    asi: { primary: 'str', secondary: 'con' },
    equipment: ['Insigne de rang', 'Trophée pris sur un ennemi vaincu', 'Habits ordinaires', '10 po'],
  },
  wayfarer: {
    name: 'Vagabond',
    description: 'Vous avez beaucoup voyagé et appris à vivre de votre ingéniosité.',
    skills: ['Perspicacité', 'Discrétion'],
    tools: ['Outils de voleur'],
    feat: 'Chanceux',
    asi: { primary: 'dex', secondary: 'wis' },
    equipment: ['Sac de couchage', 'Jeu de société', 'Vêtements de voyage', '16 po'],
  },
}
